server:
  port: ${LIFEOS_USER_SERVICE_PORT:8081}

spring:
  application:
    name: lifeos-user-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_JDBC_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DATABASE}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
