server:
  port: ${LIFEOS_TASK_SERVICE_PORT:8082}

spring:
  application:
    name: lifeos-task-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
  datasource:
    url: ${MYSQL_JDBC_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

rocketmq:
  name-server: ${ROCKETMQ_NAMESRV_ADDR}
  producer:
    group: ${spring.application.name}-producer

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
