<template>
  <div class="ai-view">
    <div class="hero">
      <h1>AI Assistant</h1>
      <p>LifeOS currently supports automatic note summaries. Save a note to trigger a summary.</p>
    </div>

    <div class="info-grid">
      <section class="info-card">
        <h2>Current capability</h2>
        <p>Note summaries are generated by `lifeos-ai-service` and written back into your note detail.</p>
      </section>

      <section class="info-card">
        <h2>Fallback mode</h2>
        <p>If no external AI key is configured, the service returns a local mock summary so the flow still works.</p>
      </section>
    </div>
  </div>
</template>

<style scoped>
.ai-view {
  max-width: 960px;
  margin: 0 auto;
  padding: 40px;
}

.hero {
  padding: 32px;
  border-radius: 24px;
  color: white;
  background: linear-gradient(135deg, #0f172a 0%, #0369a1 100%);
  box-shadow: 0 20px 40px rgba(3, 105, 161, 0.18);
  margin-bottom: 24px;
}

.hero h1 {
  margin: 0 0 12px 0;
  font-size: 36px;
}

.hero p {
  margin: 0;
  color: rgba(255, 255, 255, 0.82);
  font-size: 16px;
}

.info-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: 20px;
}

.info-card {
  background: white;
  border: 1px solid #e2e8f0;
  border-radius: 20px;
  padding: 24px;
  box-shadow: 0 10px 25px rgba(15, 23, 42, 0.05);
}

.info-card h2 {
  margin: 0 0 10px 0;
  font-size: 20px;
  color: #0f172a;
}

.info-card p {
  margin: 0;
  color: #475569;
  line-height: 1.7;
}

@media (max-width: 768px) {
  .ai-view {
    padding: 20px;
  }

  .hero {
    padding: 24px;
  }
}
</style>
