server:
  port: ${LIFEOS_BEHAVIOR_SERVICE_PORT:8085}

spring:
  application:
    name: lifeos-behavior-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
  datasource:
    url: ${MYSQL_JDBC_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

rocketmq:
  name-server: ${ROCKETMQ_NAMESRV_ADDR}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
