server.port=${LIFEOS_NOTE_SERVICE_PORT:8083}

spring.application.name=lifeos-note-service
spring.cloud.nacos.discovery.server-addr=${NACOS_SERVER_ADDR}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${MYSQL_JDBC_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
rocketmq.name-server=${ROCKETMQ_NAMESRV_ADDR}
rocketmq.producer.group=${spring.application.name}-producer

mybatis-plus.mapper-locations=classpath*:/mapper/**/*.xml
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.global-config.db-config.logic-not-delete-value=0
